# Generated by Django 2.2.1 on 2019-06-05 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.Ingredient', verbose_name='Ingredient used'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity_unit',
            field=models.CharField(blank=True, max_length=24, verbose_name='Ingredient quantity units'),
        ),
        migrations.AlterField(
            model_name='recipenote',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='recipe.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipe.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='recipe.Tag', verbose_name='Tag used'),
        ),
    ]
