# Generated by Django 2.2.1 on 2019-06-02 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20190602_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='modified_date',
            new_name='modified_time',
        ),
    ]
