# Generated by Django 2.2.1 on 2019-06-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20190605_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author_recipes', to='user.UserProfile', verbose_name='Recipe Author'),
        ),
    ]
