# Generated by Django 2.2.1 on 2019-06-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20190606_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, verbose_name='Ingredient Description'),
        ),
    ]
