# Generated by Django 2.2.1 on 2019-06-02 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20190602_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ingredient used in Recipe', 'verbose_name_plural': 'Ingredients used in Recipe'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Tag in Recipe', 'verbose_name_plural': 'Tags in Recipe'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.PositiveSmallIntegerField(default=0)),
                ('step_text', models.TextField(verbose_name='Step Directions')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe')),
            ],
            options={
                'verbose_name': 'Step in Recipe',
                'verbose_name_plural': 'Steps in Recipe',
                'unique_together': {('id', 'step_number')},
            },
        ),
    ]
