# Generated by Django 2.2.2 on 2019-06-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20190624_0131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipestep',
            unique_together=set(),
        ),
    ]
