# Generated by Django 2.2.2 on 2019-07-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_recipe_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('secret', 'Secret')], default='public', max_length=10),
        ),
    ]
