# Generated by Django 2.2.2 on 2019-07-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20190716_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipephoto',
            name='photo_file',
            field=models.FileField(blank=True, upload_to='recipe_photos'),
        ),
    ]
