# Generated by Django 2.2.2 on 2019-07-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_auto_20190716_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipephoto',
            name='photo_file',
            field=models.FileField(upload_to='recipe_photos'),
        ),
    ]
