# Generated by Django 2.2.2 on 2019-07-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_auto_20190718_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Secret', 'Secret')], default='Public', max_length=10),
        ),
    ]
