# Generated by Django 2.2.2 on 2019-07-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_auto_20190726_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipephoto',
            name='photo_file',
            field=models.CharField(max_length=400),
        ),
    ]
