# Generated by Django 2.2.2 on 2019-07-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='profile_pics/'),
        ),
    ]
