# Generated by Django 2.2.2 on 2019-07-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190715_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='profile_photos'),
        ),
    ]
