# Generated by Django 2.2.2 on 2019-07-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190716_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.FileField(blank=True, default='profile-photos/profile-pic-placeholder_500x500.png', upload_to='profile_photos'),
        ),
    ]
