# Generated by Django 2.2.2 on 2019-07-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190730_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.CharField(blank=True, default='profile-photos/profile-pic-placeholder_500x500.png', max_length=400),
        ),
    ]
